### ISSUE TITLE
why two require

### ISSUE THREAD

**Issue by wheelq** [kathgironpe/simple-sinatra-mvc#40]
`config.ru` contains:
https://github.com/kathgironpe/simple-sinatra-mvc/blob/f6dcbfb39d856d7ef374e1a7fb357d92f04fe79f/config.ru#L1

while `main.rb` contains (again):
https://github.com/kathgironpe/simple-sinatra-mvc/blob/f6dcbfb39d856d7ef374e1a7fb357d92f04fe79f/main.rb#L1

What is the reason behind this?

**Comment by kathgironpe** [comment]
Valid question. I am looking at reviewing this repo again after years off.  Dependencies should be required on config.ru.

**Comment by kathgironpe** [comment]
@wheelq I apologize for the late update. I will be changing some things in this project for educational reasons only but honestly highly recommend learning Elixir over Ruby. 

https://github.com/kathgironpe/simple-sinatra-mvc/commit/0336bc694323268ccca063315bb7949000d9c9cc
